### PR TITLE
Add UCT event review

### PR DESCRIPTION
**Pull request by SteveBarnett**

### CODE REVIEW

**Comment by SteveBarnett** [comment]
Anyone have a little time to review this, please?

@rorymckinley, @wkirschbaum, @nieldlr ? :)

**Comment by rorymckinley** [comment]
Excellent work @SteveBarnett - merged in.

**Comment by SteveBarnett** [comment]
@rorymckinley \o/. Thank you :).

**Comment by nieldlr** [comment]
Great write up @SteveBarnett! :D

**Comment by SteveBarnett** [comment]
@nieldlr Thanks! I sometimes like to make words. :)

**Pull request merged**
